const views = {
  inicio: () => `
    <div class="grid grid-4">
      <article class="card metric"><small>Cursos liberados</small><strong>24</strong><em>Catálogo ativo</em></article>
      <article class="card metric"><small>Ferramentas</small><strong>12</strong><em>Acesso do plano</em></article>
      <article class="card metric"><small>Indicações diretas</small><strong>0</strong><em>Seu link está pronto</em></article>
      <article class="card metric"><small>Comissões aprovadas</small><strong>R$ 0,00</strong><em>Regras ainda configuráveis</em></article>
    </div>
    <div class="grid grid-2 section">
      <article class="card"><div class="section-head"><h2>Seu link de indicação</h2><span class="pill">Pessoal</span></div><p style="color:#8f96a3;font-size:12px">Compartilhe quando o programa estiver ativado pelo administrador.</p><div class="copybox"><code id="refLink">https://seudominio.com.br/?ref=FERNANDO01</code><button class="button" onclick="copyRef()">Copiar</button></div></article>
      <article class="card"><div class="section-head"><h2>Progresso das trilhas</h2><span class="pill">Demonstração</span></div><div class="progress-list"><div class="progress-row"><span>Fundamentos do Digital</span><div class="bar"><span style="width:68%"></span></div><b>68%</b></div><div class="progress-row"><span>Produtividade com IA</span><div class="bar"><span style="width:35%"></span></div><b>35%</b></div><div class="progress-row"><span>Vendas e Atendimento</span><div class="bar"><span style="width:15%"></span></div><b>15%</b></div></div></article>
    </div>
    <section class="section"><div class="section-head"><h2>Continue aprendendo</h2><span class="pill">Mais recentes</span></div><div class="course-list">${courseCards()}</div></section>`,
  cursos: () => `<div class="section-head"><h2>Biblioteca de cursos</h2><span class="pill">24 conteúdos</span></div><div class="course-list">${courseCards()}${courseCards()}</div>`,
  ferramentas: () => `<div class="section-head"><h2>Ferramentas digitais</h2><span class="pill">Área protegida</span></div><div class="tool-grid">${tool('Calculadora de metas','Planeje objetivos e acompanhe indicadores.')}${tool('Gerador de textos','Modelos de copy para redes sociais e atendimento.')}${tool('Biblioteca de templates','Materiais editáveis para sua operação.')}${tool('Central de links','Organize recursos importantes em um só lugar.')}${tool('Checklist comercial','Processo prático de acompanhamento de clientes.')}${tool('Painel de produtividade','Monitore suas tarefas e prioridades.')}</div>`,
  ias: () => `<div class="section-head"><h2>Hub de inteligências artificiais</h2><span class="pill">Configurável</span></div><div class="tool-grid">${tool('Assistente de conteúdo','Ajuda para ideias, roteiros e textos.')}${tool('Assistente de vendas','Estruture abordagens e respostas comerciais.')}${tool('Assistente de estudos','Resumos, planos de estudo e organização.')}${tool('Prompts exclusivos','Biblioteca interna de prompts do clube.')}${tool('Analisador de ofertas','Estruture benefícios e diferenciais de produtos.')}${tool('Planejador semanal','Transforme objetivos em ações práticas.')}</div>`,
  rede: () => `<div class="grid grid-2"><article class="card network-demo"><span class="line ln1"></span><span class="line ln2"></span><span class="line ln3"></span><span class="line ln4"></span><span class="line ln5"></span><span class="line ln6"></span><span class="node root">VOCÊ</span><span class="node l1">A</span><span class="node l2">B</span><span class="node s1">A1</span><span class="node s2">A2</span><span class="node s3">B1</span><span class="node s4">B2</span></article><article class="card"><div class="section-head"><h2>Resumo da rede</h2><span class="pill">Exemplo</span></div><div class="grid"><div class="metric"><small>Nível 1</small><strong>0</strong></div><div class="metric"><small>Nível 2</small><strong>0</strong></div><p style="color:#8f96a3;font-size:12px;line-height:1.6">O sistema real só exibirá níveis habilitados nas regras de comissão definidas pelo administrador.</p></div></article></div>`,
  comissoes: () => `<article class="card"><div class="section-head"><h2>Histórico de comissões</h2><span class="pill">Rastreável</span></div><div class="table-wrap"><table class="table"><thead><tr><th>Data</th><th>Origem</th><th>Nível</th><th>Valor</th><th>Status</th></tr></thead><tbody><tr><td colspan="5" class="empty">Nenhuma comissão registrada nesta demonstração.</td></tr></tbody></table></div></article>`,
  assinatura: () => `<div class="grid grid-2"><article class="card"><div class="section-head"><h2>Sua assinatura</h2><span class="status">ATIVA</span></div><p style="color:#8f96a3;line-height:1.6">O valor, ciclo de cobrança e meio de pagamento serão definidos no novo projeto antes da publicação.</p><button class="button">Gerenciar assinatura</button></article><article class="card"><div class="section-head"><h2>Benefícios liberados</h2><span class="pill">Plano atual</span></div><div class="progress-list"><div>✓ Biblioteca de cursos</div><div>✓ Ferramentas digitais</div><div>✓ Hub de IAs</div><div>✓ Link individual de indicação</div></div></article></div>`
};

function courseCards(){return `<article class="card course"><div class="course-cover"></div><div class="course-body"><h3>Fundamentos do Digital</h3><p>Base para começar com organização e estratégia.</p></div></article><article class="card course"><div class="course-cover"></div><div class="course-body"><h3>Produtividade com IA</h3><p>Use inteligência artificial para ganhar tempo.</p></div></article><article class="card course"><div class="course-cover"></div><div class="course-body"><h3>Vendas e Atendimento</h3><p>Melhore sua comunicação e acompanhamento.</p></div></article>`}
function tool(name,desc){return `<article class="card tool-card"><span class="pill">MEMBROS</span><b>${name}</b><p>${desc}</p><button class="button">Abrir</button></article>`}
function copyRef(){navigator.clipboard?.writeText(document.getElementById('refLink').textContent);}

const labels={inicio:'Visão geral',cursos:'Cursos',ferramentas:'Ferramentas',ias:'IAs',rede:'Minha rede',comissoes:'Comissões',assinatura:'Assinatura'};
function render(name){document.getElementById('pageTitle').textContent=labels[name];document.getElementById('view').innerHTML=views[name]();document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===name));}
document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>render(b.dataset.view));render('inicio');
